spring:
    application:
        name: FootballManager

    datasource:
        url: jdbc:postgresql://localhost:5432/football_manager
        username: football_admin
        password: secret
        driver-class-name: org.postgresql.Driver

    jpa:
        open-in-view: false
        properties:
            hibernate:
                default_schema: football
        hibernate:
            ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    flyway:
        schemas: football

    cache:
        type: caffeine
        caffeine:
            spec: maximumSize=500,expireAfterWrite=10m

